## Import NumPy

In [2]:
import numpy as np

print(np.__version__)

1.20.1


## How to create a 1D array

In [3]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


## How to create a boolean array

In [4]:
import numpy as np
arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## How to extract items that satisfy a given condition from 1D array

In [5]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[arr % 2 == 1]
print(result)

[1 3 5 7 9]


## How to replace items that satisfy a condition with another value in numpy array

In [6]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## How to compute the mean, median, standard deviation of a numpy array

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
mu = np.mean(arr)
med = np.median(arr)
sd = np.std(arr)
print(mu)
print(med)
print(sd)

5.5
5.5
2.8722813232690143


## How to find the percentile scores of a numpy array

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
percentiles = [5, 95]
result = np.percentile(arr, q=percentiles)
print(result)

[1.45 9.55]


## How to find the most frequent value in a numpy array

In [13]:
arr = np.array([3, 4, 2, 1, 1, 1, 2, 3, 1, 3])
values, counts = np.unique(arr, return_counts=True)
result = values[np.argmax(counts)]
print(result)

1


## How to stack two arrays vertically

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
out = np.vstack((a,b))
print(out)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## How to stack two arrays horizontally

In [17]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
out = np.hstack((a,b))
print(out)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## How to get the common items between two python numpy arrays

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
out = np.intersect1d(a,b)
print(out)

[2 4]


## How to remove from one array those items that exist in another

In [19]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])  
out = np.setdiff1d(a,b)
print(out)

[1 2 3 4]


## How to get the positions where elements of two arrays match

In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
out = np.where(a == b)[0]
print(out)

[1 3 5 7]


## How to reverse the columns of a 2D array

In [21]:
arr = np.array([[3, 4, 5], [0, 1, 2], [6, 7, 8]]) 
out = arr[:, ::-1]
print(out)

[[5 4 3]
 [2 1 0]
 [8 7 6]]


## How to normalize an array so the values range exactly between 0 and 1

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_norm = (arr - np.min(arr)) / (np.max(arr - np.min(arr)))
print(arr_norm)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## How to find the correlation between two columns of a numpy array

In [23]:
matr = np.array([[0, 0, 0, 2, 2],
                 [0, 2, 1, 2, 2],
                 [2, 2, 1, 0, 0],
                 [0, 0, 2, 0, 1],
                 [1, 2, 2, 0, 0]])
x = 0
y = 3
corr = np.corrcoef(matr[:, x], matr[:, y])[0, 1]
print(corr)

-0.6123724356957946


## How to find if a given array has any null values

In [24]:
matr = np.array([[1.0, 2.0], [np.nan, 4.0]]) 
flag = np.isnan(matr).any()
print(flag)

True


## How to find the count of unique values in a numpy array

In [25]:
arr = np.array([1,2,3,1,2,4]) 
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)

[1 2 3 4]


## How to find the maximum value in each row of a numpy array 2d

In [26]:
a = np.array([[9, 9, 4], [8, 8, 1], [5, 3, 6]]) 
maximas = np.amax(a, axis=1)
print(maximas)

[9 8 6]


## How to drop all missing values from a numpy array

In [27]:
import numpy as np
a = np.array([1,2,3,np.nan,5,6,7,np.nan]) 
after_drop = a[~np.isnan(a)]
print(after_drop)

[1. 2. 3. 5. 6. 7.]
